
<?php

$this->leftSideBar()->setItems([
    [
        'id' => 'home',
        'label' => 'Home',
        'link' => $this->url('home'),
        'class' => 'active',
    ],
    [
        'id' => 'manula-search',
        'label' => 'Manual Search',
        'link' => $this->url("application", ['action' => 'manual-search'])
    ],
//    [
//        'id' => 'support',
//        'label' => 'Support',
//        'dropdown' => [
//            [
//                'id' => 'documentation',
//                'label' => 'Documentation',
//                'link' => $this->url('application', ['page' => 'contents'])
//            ],
//            [
//                'id' => 'help',
//                'label' => 'Help',
//                'link' => $this->url('application', ['page' => 'help'])
//            ]
//        ]
//    ],
//    [
//        'id' => 'about',
//        'label' => 'About',
//        $this->url('home')
//    ],
]);

echo $this->leftSideBar()->render();