<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Search Jobs</span></a>
        </div>

        <div class="clearfix"></div>
        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath() . '/application/manual-search' ?>">Manual Search</a>
                    </li>

                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>

<?php

$this->leftSideBar()->setItems([
    [
        'id' => 'home',
        'label' => 'Home',
        'link' => $this->url('home')
    ],
    [
        'id' => 'downloads',
        'label' => 'Downloads',
        'link' => $this->url("application", ['action' => 'downloads'])
    ],
    [
        'id' => 'support',
        'label' => 'Support',
        'dropdown' => [
            [
                'id' => 'documentation',
                'label' => 'Documentation',
                'link' => $this->url('application', ['page' => 'contents'])
            ],
            [
                'id' => 'help',
                'label' => 'Help',
                'link' => $this->url('application', ['page' => 'help'])
            ]
        ]
    ],
    [
        'id' => 'about',
        'label' => 'About',
        $this->url('home')
    ],
]);

//echo $this->leftSideBar()->render();