<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <h2 id="page-title" class="col-md-2" style="padding-top: 9px;"></h2>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <img src="<?php echo $this->basePath() . '/img/img.jpg'; ?>" alt="">John Doe
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Comming Soon</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="<?php echo $this->basePath() . '/application/bookmarks' ?>" title="Bookmarks">
                        <i class="fa fa-star"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>