<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Search Jobs')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('build/css/custom.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.css'))
        ->prependStylesheet($this->basePath('vendors/jqvmap/dist/jqvmap.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'))
        ->prependStylesheet($this->basePath('vendors/nprogress/nprogress.css'))
        ->prependStylesheet($this->basePath('vendors/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('vendors/nprogress/nprogress.js'))
        ->prependFile($this->basePath('vendors/fastclick/lib/fastclick.js'))
        ->prependFile($this->basePath('vendors/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/jquery/dist/jquery.min.js'))

    ?>

</head>
<body class="nav-md">

<div class="container body">
    <div class="main_container">
        <?php
        echo $this->render('partials/left-sidebar.phtml');
        echo $this->render('partials/top-nav.phtml');
        ?>


        <div class="right_col" role="main">
            <?php echo $this->content ?>
        </div>
        <!-- footer content -->
        <footer>

            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
