<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Awesome Jobs From Worldwide')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', 'Awesome jobs from worldwide! Find jobs in one place from Github Jobs, StackOverflow jobs. This is open source project.')
        ->appendName('keywords', 'AWESOME JOBS, JOB CRAWLER, OPEN SOURCE, PHP, JAVA')
        ->appendName('author', 'Hayk Manasyan')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('build/css/custom.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.css'))
        ->prependStylesheet($this->basePath('vendors/jqvmap/dist/jqvmap.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'))
        ->prependStylesheet($this->basePath('vendors/nprogress/nprogress.css'))
        ->prependStylesheet($this->basePath('vendors/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bookmark.js'))
        ->prependFile($this->basePath('js/app.js'))
        ->prependFile($this->basePath('vendors/nprogress/nprogress.js'))
        ->prependFile($this->basePath('vendors/fastclick/lib/fastclick.js'))
        ->prependFile($this->basePath('vendors/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/jquery/dist/jquery.min.js'))

    ?>

</head>
<body class="nav-md">
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-106372487-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', 'UA-106372487-1');
</script>
<div class="container body">
    <div class="main_container">
        <?php
        echo $this->render('partials/left-sidebar.phtml');
        echo $this->render('partials/top-nav.phtml');
        ?>

        <div class="right_col" role="main">
            <?php echo $this->content ?>
        </div>

    </div>
</div>
<!-- Custom Theme Scripts -->
<script src="<?php echo $this->basePath() . '/build/js/custom.min.js' ?>"></script>


<?php echo $this->inlineScript() ?>
</body>
</html>
