<div class="row tile_count">
<?php
foreach ( $this->totalCount as $key => $count ) : ?>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><?php echo mb_strtoupper($key) ?></span>
        <div class="count"><?php echo $count; ?></div>
    </div>
<?php
endforeach;
?>
</div>
<div class="row">
    <?php
    if ( isset($this->jobs) && is_array($this->jobs) && count($this->jobs) ) :
        $s = 0;
        foreach ( $this->jobs as $key => $job ) :
            $d = $s / 2;
            if ( is_int($d) )  : ?>
                <div class="row">
                <?php
            endif;
            ?>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2> Last 5 <?php echo mb_strtoupper($key) ?> JOBS </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="<?php echo $this->basePath() . '/application/search/' . urlencode($key); ?>">Full
                                    List</a>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Location</th>
                                <th>Type</th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ( $job as $value ) :
                                ?>
                                <tr >
                                    <td><?php echo $value->getTitle(); ?></td>
                                    <td><?php echo $value->getLocation(); ?></td>
                                    <td><?php echo $value->getType(); ?></td>
                                    <td>
                                        <a class="btn btn-info"
                                           href="<?php echo $this->basePath() . '/application/detail/' . $value->getId(); ?>">
                                            More </a>
                                    </td>
                                </tr>
                            <?php endforeach;;
                            ?>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <?php
            if ( !is_int($d) ) : ?>
                </div>
                <?php
            endif;
            $s++;
        endforeach;

    endif;
    ?>
</div>
