<div class="row">
    <?php
    if ( isset($this->jobs) && is_array($this->jobs) && count($this->jobs) ) :
        $s = 0;
        foreach ( $this->jobs as $key => $job ) :
            $d = $s / 2;
            if ( is_int($d) )  : ?>
                <div class="row">
                <?php
            endif;
            ?>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2> Last 5 <?php echo mb_strtoupper($key) ?> JOBS </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="<?php echo $this->basePath() . '/application/search/' . urlencode($key); ?>">Full
                                    List</a>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Company</th>
                                <th>Title</th>
                                <th>Location</th>
                                <th>Type</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ( $job as $value ) :
                                ?>
                                <tr>
                                    <th scope="row"><?php echo $value->getCompany(); ?></th>
                                    <td><?php echo $value->getTitle(); ?></td>
                                    <td><?php echo $value->getLocation(); ?></td>
                                    <td><?php echo $value->getType(); ?></td>
                                </tr>
                            <?php endforeach;;
                            ?>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <?php
            if ( !is_int($d) ) : ?>
                </div>
                <?php
            endif;
            $s++;
        endforeach;

    endif;
    ?>
</div>
