<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <table id="datatable" class="table table-hover">
                    <thead>
                    <tr>
                        <th>Company</th>
                        <th>Title</th>
                        <th>Location</th>
                        <th>Type</th>
                        <th> </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->result as $k => $res) :

                        ?>
                        <tr>
                            <th scope="row"><?php echo $res['company']; ?></th>
                            <td><?php echo $res['title']; ?></td>
                            <td><?php echo $res['location']; ?></td>
                            <td><?php echo $res['type']; ?></td>
                            <td>
                                <a class="btn btn-info" href="<?php echo $this->basePath() . '/application/detail/' . $res['id']; ?>"> More </a>
                            </td>
                        </tr>

                    <?php endforeach;;
                    ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>


<?php
$this->inlineScript()->captureStart();

echo $this->headScript()
    ->appendFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
    ->appendFile($this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
    ->appendFile($this->basePath('build/js/custom.min.js'));
?>
<script>
//    $(document).ready(function () {
//        $('#datatable').dataTable();
//    });
</script>
<?php

$this->inlineScript()->captureEnd();

?>


